name: Quality

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, ready_for_review ]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --no-audit --no-fund

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Check unused dependencies
      run: npm run check-deps

    - name: Run spell check
      run: |
        npx cspell link add @cspell/dict-pt-br
        npx cspell --no-must-find-files --config ./cspell.json '**/*.{md,mdx}'

    - name: Build project
      run: npm run build
